fixtures:
  symlinks:
    gitlab: "#{source_dir}"
  repositories:
    git:
      repo: "git://github.com/puppetlabs/puppetlabs-git.git"
      ref: "0.0.3"
    rbenv:
      repo: "git://github.com/alup/puppet-rbenv.git"
      ref: "6628a24"
    stdlib:
      repo: "git://github.com/puppetlabs/puppetlabs-stdlib.git"
      ref: "4.2.1"
    vcsrepo:
      repo: "git://github.com/puppetlabs/puppetlabs-vcsrepo.git"
      ref: "0.2.0"
