name    'sbadia-gitlab'
version '0.0.10'
source  'https://github.com/sbadia/puppet-gitlab'
author  'Andrew Tomaka, Steffen Roegner, Uwe Kleinmann, Matt Klich, Sebastien Badia'
license 'GPLv3'
summary 'Puppet GitLab Module'
description 'Module to install GitLab using puppet'
project_page 'https://github.com/sbadia/puppet-gitlab/'
dependency 'puppetlabs/stdlib'
#dependency 'sbadia/gitlab_requirements', '>= 0.2.0'
