name    'puppet-gitlab'
version '0.0.8'
source  'https://github.com/sbadia/puppet-gitlab'
author  'Steffen Roegner, Uwe Kleinmann, Matt Klich, Sebastien Badia'
license 'GPLv3'
summary 'Puppet GitLab Module'
description 'Module to install GitLab using puppet'
project_page 'https://github.com/sbadia/puppet-gitlab/'
dependency 'puppetlabs/mysql', '>= 0.6.1'
dependency 'puppetlabs/stdlib', '>= 4.1.0'
dependency 'fsalum/redis', '>= 0.0.5'
dependency 'puppetlabs/nginx', '>= 0.0.1'
dependency 'puppetlabs/ruby', '>= 0.0.2'
