#!/bin/sh
# MANAGED BY PUPPET
# Module:: gitlab
#
while read oldrev newrev refname
do
  # Personals Hooks
  /usr/bin/git config hooks.mailinglist > /dev/null 2>&1
  if [ "$?" -eq "0" ]
  then
    echo "* hook.email to $(/usr/bin/git config hooks.mailinglist)"
    echo $oldrev $newrev $refname | . /usr/share/doc/git-core/contrib/hooks/post-receive-email
  fi

  # Gitlab Hooks
  # For every branch or tag that was pushed, create a Resque job in redis.
  pwd=`pwd`
  reponame=`basename "$pwd" | sed s/\.git$//`
  env -i redis-cli rpush "resque:queue:post_receive" "{\"class\":\"PostReceive\",\"args\":[\"$reponame\",\"$oldrev\",\"$newrev\",\"$ref\",\"$GL_USER\"]}" > /dev/null 2>&1

done

# Custom Hooks
if [ -f ./hooks/custom-hook ]
then
  echo "* hook.custom"
  ./hooks/custom-hook
fi
